//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj11_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> productPrice { get; set; }
        public Nullable<int> productCount { get; set; }
        public string productType { get; set; }
        public Nullable<System.DateTime> productDate { get; set; }
        public string productArea { get; set; }
    }
}
